// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcxURjO0QMTDl-iUZcWTcjwulK_OH0pf4',
    appId: '1:420099235195:web:af1462b4f260109b7231de',
    messagingSenderId: '420099235195',
    projectId: 'eestieco-be8e9',
    authDomain: 'eestieco-be8e9.firebaseapp.com',
    storageBucket: 'eestieco-be8e9.firebasestorage.app',
    measurementId: 'G-EGXV8SF9KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8E2XK1eM85uMJk5IhbhEnwqQZ4QD_EBA',
    appId: '1:420099235195:android:5a625986a04120787231de',
    messagingSenderId: '420099235195',
    projectId: 'eestieco-be8e9',
    storageBucket: 'eestieco-be8e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY9r14mnbb7TqpI8LIjtCIG5ePJuU83_0',
    appId: '1:420099235195:ios:a5590867f49076e17231de',
    messagingSenderId: '420099235195',
    projectId: 'eestieco-be8e9',
    storageBucket: 'eestieco-be8e9.firebasestorage.app',
    iosBundleId: 'com.example.eestiEco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY9r14mnbb7TqpI8LIjtCIG5ePJuU83_0',
    appId: '1:420099235195:ios:a5590867f49076e17231de',
    messagingSenderId: '420099235195',
    projectId: 'eestieco-be8e9',
    storageBucket: 'eestieco-be8e9.firebasestorage.app',
    iosBundleId: 'com.example.eestiEco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcxURjO0QMTDl-iUZcWTcjwulK_OH0pf4',
    appId: '1:420099235195:web:68a3ad4d2d9013297231de',
    messagingSenderId: '420099235195',
    projectId: 'eestieco-be8e9',
    authDomain: 'eestieco-be8e9.firebaseapp.com',
    storageBucket: 'eestieco-be8e9.firebasestorage.app',
    measurementId: 'G-TSJNMEY0WL',
  );

}